
package es.udc.ws.app.client.service.soap.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OfertaProviderService", targetNamespace = "http://soap.ws.udc.es/", wsdlLocation = "file:/home/user/Escritorio/Universidad/Terceiro/Practicas/ISD/Eclipse/ws-app/ws-app-service/target/generated-sources/wsdl/OfertaProviderService.wsdl")
public class OfertaProviderService
    extends Service
{

    private final static URL OFERTAPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException OFERTAPROVIDERSERVICE_EXCEPTION;
    private final static QName OFERTAPROVIDERSERVICE_QNAME = new QName("http://soap.ws.udc.es/", "OfertaProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/user/Escritorio/Universidad/Terceiro/Practicas/ISD/Eclipse/ws-app/ws-app-service/target/generated-sources/wsdl/OfertaProviderService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OFERTAPROVIDERSERVICE_WSDL_LOCATION = url;
        OFERTAPROVIDERSERVICE_EXCEPTION = e;
    }

    public OfertaProviderService() {
        super(__getWsdlLocation(), OFERTAPROVIDERSERVICE_QNAME);
    }

    public OfertaProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OFERTAPROVIDERSERVICE_QNAME, features);
    }

    public OfertaProviderService(URL wsdlLocation) {
        super(wsdlLocation, OFERTAPROVIDERSERVICE_QNAME);
    }

    public OfertaProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OFERTAPROVIDERSERVICE_QNAME, features);
    }

    public OfertaProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OfertaProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OfertaProvider
     */
    @WebEndpoint(name = "OfertaProviderPort")
    public OfertaProvider getOfertaProviderPort() {
        return super.getPort(new QName("http://soap.ws.udc.es/", "OfertaProviderPort"), OfertaProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OfertaProvider
     */
    @WebEndpoint(name = "OfertaProviderPort")
    public OfertaProvider getOfertaProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.ws.udc.es/", "OfertaProviderPort"), OfertaProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OFERTAPROVIDERSERVICE_EXCEPTION!= null) {
            throw OFERTAPROVIDERSERVICE_EXCEPTION;
        }
        return OFERTAPROVIDERSERVICE_WSDL_LOCATION;
    }

}
